describe('fensteraudio', function()
	local fensteraudio = require('fensteraudio')

	describe('fensteraudio.open(...)', function()
		it('should return a audiodevice userdata #needsspeaker', function()
			local audiodevice = fensteraudio.open()
			finally(function() audiodevice:close() end)
			assert.is_userdata(audiodevice)
		end)
	end)
end)
